version: 2.1
jobs:
  test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: fastlane scan
  deploy:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: xcodebuild -project CurrencyExchange.xcodeproj -scheme CurrencyExchange -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.3' test | xcbeautify

workflows:
  test_release:
    jobs:
      - deploy
