version: 2.1
jobs:
  test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: fastlane scan
  deploy:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: xcodebuild "build-for-testing" "-project" "CurrencyExchange.xcodeproj" "-scheme" "CurrencyConverter" "-configuration" "Debug" "-destination" "generic/platform=iOS" "-xcconfig" | xcpretty

workflows:
  test_release:
    jobs:
      - deploy
