version: 2.1
jobs:
  test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: fastlane scan
  deploy:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: 
            device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
            xcodebuild -project CurrencyExchange.xcodeproj -scheme CurrencyExchange -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$device' test | xcpretty

workflows:
  test_release:
    jobs:
      - deploy